{% set name = "open-fonts" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kiwi0fruit/open-fonts/releases/download/{{ version }}/open-fonts.tar.bz2
  sha256: 19d1cb8e953d3e1072c7d42123a37d9b5b2fae6f3c0b078e310338c89e3634db

build:
  number: 2
  noarch: generic

test:
  commands:
    - test -f $PREFIX/fonts/open-fonts/Symbola.ttf  # [unix]

about:
  home: https://github.com/kiwi0fruit/open-fonts
  license: MIT AND Apache-2.0 AND OFL-1.1 AND LicenseRef-Symbola-Public-Domain AND LicenseRef-DejaVu-Fonts
  license_family: OTHER
  license_file: LICENSE
  summary: A collection of beautiful free and open source fonts
  description: |
    This package is an aggregate of several fonts with various free and open source
    licenses. See $PREFIX/fonts/open-fonts/LICENSE directory for details.
    * MIT License - CSS files,
    * Apache License 2.0 - Cousine, Open Sans, Robotization Mono, Roboto,
    * DejaVu Fonts License - DejaVu Sans, DejaVu Sans Mono, DejaVuSerif,
    * Symbola Public Domain - Symbola 10.23,
    * SIL Open Font License 1.1 -
      Amiri, DavidLibre, IBM Plex Mono, Halant, Inconsolata Sugar, Lato, Linus Libertini, Noto Sans,
      Noto Sans Arabic, Noto Sans Devanagari, Noto Sans Hebrew, Noto Sans Mono, Noto Serif,
      Noto Serif Devanagari, Source Sans Pro, Source Serif Pro, Sourcing Code Pro, Sourcing Sans Pro,
      ST1X Two Math, ST1X Two Text, STIX Two Math, STIX Two Text, Vollkorn.
  doc_url: https://github.com/kiwi0fruit/open-fonts
  dev_url: https://github.com/kiwi0fruit/open-fonts

extra:
  recipe-maintainers:
    - kiwi0fruit
