{% set name = "open-fonts" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kiwi0fruit/open-fonts/releases/download/{{ version }}/open-fonts.tar.bz2
  sha256: 19a1efab8ae1fa7b5fe21fbf3796b4a6eca736540f521ac847c2034f852fbc2f

build:
  number: 1
  noarch: generic

test:
  commands:
    - test -f $PREFIX/fonts/open-fonts/Symbola.ttf  # [unix]

about:
  home: https://github.com/kiwi0fruit/open-fonts
  license: MIT AND Apache-2.0 AND OFL-1.1 AND CC-BY-4.0 AND LicenseRef-Symbola-Public-Domain AND LicenseRef-DejaVu-Fonts
  license_family: OTHER
  license_file: LICENSE
  summary: A collection of beautiful free and open source fonts
  description: |
    This package is an aggregate of several fonts with various free and open source
    licenses. See $PREFIX/fonts/open-fonts/LICENSE directory for details.
    * MIT License - CSS files,
    * Apache License 2.0 - Cousine, Open Sans, Roboto, Roboto Mono, Robotization Mono, Twemoji Mozilla,
    * DejaVu Fonts License - DejaVu Sans, DejaVu Sans Mono, DejaVu Serif,
    * CC BY 4.0 - Twemoji Mozilla,
    * Symbola Public Domain - Symbola 10.23,
    * SIL Open Font License 1.1 -
      Amiri, Catamaran, David Libre, IBM Plex Mono, Halant, Inconsolata Sugar, Kawkab Mono, Lato,
      Libertinus Math, Libertinus Serif, Linus Libertinus, Linus Libertinus Math, Noto Naskh Arabic,
      Noto Nastaliq Urdu, Noto Sans, Noto Sans Arabic, Noto Sans Armenian, Noto Sans Bengali,
      Noto Sans Georgian, Noto Sans Devanagari, Noto Sans Hebrew, Noto Sans Mono, Noto Sans Tamil,
      Noto Sans Thai, Noto Serif, Noto Serif Armenian, Noto Serif Bengali, Noto Serif Georgian,
      Noto Serif Devanagari, Noto Serif Tamil, Noto Serif Thai, Source Code Pro, Source Sans Pro,
      Source Serif Pro, Sourcing Code Pro, Sourcing Sans Pro, STIX Two Math, STIX Two Text,
      Vollkorn, XITS, XITS Math, XITS One Math, XITS One Text, XITS Two Math, XITS Two Text.
  doc_url: https://github.com/kiwi0fruit/open-fonts
  dev_url: https://github.com/kiwi0fruit/open-fonts

extra:
  recipe-maintainers:
    - kiwi0fruit
